---
name: OpenAPI
on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  check-aep-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Install Spectral
        run: npm i @stoplight/spectral-cli -g
      - name: Check that OpenAPI conforms to AEP guidelines
        run: spectral lint -r api/.spectral.yaml api/*.yaml
